name: Build & push to Viaplay ECR
on:
  # push:
  #   paths:
  #     - Dockerfile
  #     - docker-bake.hcl
  #     - '**.conf'
  #     - '**.lua'
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  build-push:
    name: Build & push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # - name: Create Build Number
      #   id: create-build-number
      #   uses: nentgroup/action-buildnumber@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ secrets.GHA_DEV_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2

      - name: Build binaries for both architectures
        run: |
          make amd64-build amd64-build-healthcheck
          make arm64-build arm64-build-healthcheck

      - name: Build and push multi-arch Docker image
        run: |
          VERSION=$(cat VERSION)
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg BUILDMODE=copy \
            --push \
            -t 51980963131.dkr.ecr.eu-west-1.amazonaws.com/awscollector:${VERSION} \
            -f ./cmd/awscollector/Dockerfile .

      # - name: Extract metadata for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ steps.login-ecr.outputs.registry }}/mtg/ecs-fluent-bit-forwarder
      #     tags: |
      #       type=sha,format=short
      #       type=raw,value=${{ steps.create-build-number.outputs.build-number }}
      #       type=raw,value=latest,enable=${{ github.ref_name == github.event.repository.default_branch }}
      #       type=raw,value=${{ github.ref_name }}
      #       type=raw,value=${{ github.ref_name }}--${{ steps.create-build-number.outputs.build-number }}
      #       type=raw,value=${{ github.ref_name }}--latest

      # - name: Build and push with Docker Bake
      #   uses: docker/bake-action@v5
      #   env:
      #     DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #   with:
      #     files: |
      #       ./docker-bake.hcl
      #       ${{ steps.meta.outputs.bake-file }}
      #     targets: service
      #     push: true
      #     provenance: false

      # - name: Create GitHub Release
      #   if: github.ref == 'refs/heads/main'
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: ecs-fluent-bit-forwarder-${{ steps.create-build-number.outputs.build-number }}
      #     name: ECS Fluent Bit Logs Forwarder ${{ steps.create-build-number.outputs.build-number }}
      #     generate_release_notes: true
      #
