# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

name: C/D

on:        
  workflow_dispatch:
    inputs:
      version:
        description: 'the version number to release'
        required: true
      sha:
        description: 'the github sha to release'
        required: true
    
env:
  IMAGE_NAME: aws-otel-collector
  IMAGE_NAMESPACE: amazon
  PACKAGING_ROOT: build/packages
  ECR_REPO_INTEGRATION_TEST: aws-otel-test/adot-collector-integration-test
  ECR_REPO: aws-observability/aws-otel-collector
  PACKAGE_CACHE_KEY: "cached_tested_packages_${{ github.run_id }}"
  SSM_RELEASE_S3_BUCKET: "aws-otel-collector-ssm"
  SSM_RELEASE_PACKAGE_NAME: "AWSDistroOTel-Collector"
  RELEASE_S3_BUCKET: "aws-otel-collector"

jobs:
  release-checking: 
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.checking_sha_version.outputs.version }}
      testing_version: ${{ steps.checking_sha_version.outputs.testing_version }}
      latest-or-newer: ${{ steps.version.outputs.latest-or-newer }}
    steps: 
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.INTEG_TEST_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.INTEG_TEST_AWS_KEY_SECRET }}
          aws-region: us-west-2

      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_RELEASE_USERNAME }}
          password: ${{ secrets.DOCKERHUB_RELEASE_TOKEN }}

      - name: Download candidate
        run: aws s3 cp "s3://aws-otel-collector-release-candidate/${{ github.event.inputs.sha }}.tar.gz" candidate.tar.gz

      - name: Uncompress the candidate package
        run: tar zxvf candidate.tar.gz

      - name: Check commit SHA and version
        id: checking_sha_version
        run: |
          version_in_release=`cat $PACKAGING_ROOT/VERSION`
          version_in_release_candidate=`cat $PACKAGING_ROOT/TESTING_VERSION`
          sha_in_candidate=`cat $PACKAGING_ROOT/GITHUB_SHA`

          if [ $version_in_release != ${{ github.event.inputs.version }} ]; then
            echo "::error::Wrong version is detected: $version_in_release != ${{ github.event.inputs.version }}"
            exit 1
          fi
          if [ $sha_in_candidate != ${{ github.event.inputs.sha }} ]; then
            echo "::error::Wrong SHA is detected: $sha_in_candidate != ${{ github.event.inputs.sha }}"
            exit 1
          fi

          echo "::set-output name=version::$version_in_release"
          echo "::set-output name=testing_version::$version_in_release_candidate"
          
      - name: Compare version with Dockerhub latest
        id: version
        run: |
          TAG="${{ steps.checking_sha_version.outputs.version }}" 
          TARGET_VERSION=$TAG bash tools/workflow/docker-version-compare.sh

      - name: Cache packages
        uses: actions/cache@v3
        with:
          key: ${{ env.PACKAGE_CACHE_KEY }}
          path: ${{ env.PACKAGING_ROOT }}

  release-to-s3:
    runs-on: ubuntu-latest
    needs: [release-checking]
    steps:
      - uses: actions/checkout@v3

      - name: Restore cached packages
        uses: actions/cache@v3
        with:
          key: ${{ env.PACKAGE_CACHE_KEY }}
          path: ${{ env.PACKAGING_ROOT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.RELEASE_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RELEASE_SECRET }}
          aws-region: us-west-2

      - name: Release to S3
        run: s3_bucket_name=${{ env.RELEASE_S3_BUCKET }} upload_to_latest=0 bash tools/release/image-binary-release/s3-release.sh

      - name: Release binaries to s3 with latest version
        if: ${{ needs.release-checking.outputs.latest-or-newer == 'true' }}
        run: s3_bucket_name=${{ env.RELEASE_S3_BUCKET }} upload_to_latest=1 bash tools/release/image-binary-release/s3-release.sh
          
  release-version-image:
    runs-on: ubuntu-latest
    needs: [release-checking]
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Public Release ECR
        id: login-ecr
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.RELEASE_KEY_ID }}
          password: ${{ secrets.RELEASE_SECRET }}
        env:
          AWS_REGION: us-east-1

      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_RELEASE_USERNAME }}
          password: ${{ secrets.DOCKERHUB_RELEASE_TOKEN }}

      - name: Pull image from integration test ECR and Upload to public release ECR and Dockerhub
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: public.ecr.aws/${{ env.ECR_REPO_INTEGRATION_TEST }}:${{ needs.release-checking.outputs.testing_version }}
          dst: |
            public.ecr.aws/${{ env.ECR_REPO }}:${{ needs.release-checking.outputs.version }}
            ${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ needs.release-checking.outputs.version }}

      - name: Pull image from release ECR, tag as latest and push to public release ECR and DockerHub
        if: ${{ needs.release-checking.outputs.latest-or-newer == 'true' }}
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: public.ecr.aws/${{ env.ECR_REPO }}:${{ needs.release-checking.outputs.version }}
          dst: |
            public.ecr.aws/${{ env.ECR_REPO }}:latest
            ${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest

  release-adot-operator:
    runs-on: ubuntu-latest
    needs: [ release-version-image,release-to-s3, release-checking ]
    steps:
      #Since the tools in workflow are always up-to-date with the github workflow, we don't need to use the tools in workflows from the committed sha
      #but using the tools in workflows from the branch triggered with workflow_dispatch.
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        if: steps.release-latest-image.outputs.cache-hit != 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.RELEASE_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RELEASE_SECRET }}
          aws-region: us-west-2

      - name: Mirror ADOT operator
        if: ${{ needs.release-checking.outputs.latest-or-newer == 'true' }}
        run: cd tools/release/adot-operator-images-mirror && go run ./
        env:
          AWS_SDK_LOAD_CONFIG: true
  
  ssm-release:
    runs-on: ubuntu-latest
    needs:  [release-version-image,release-to-s3, release-checking]
    steps:
      - name: Trigger SSM package build and public
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: release SSM package
          token: ${{ secrets.REPO_WRITE_ACCESS_TOKEN }}
          inputs: '{ "version": "${{ needs.release-checking.outputs.version }}", "sha": "${{ github.event.inputs.sha }}", "public": "true", "pkgname": "${{ env.SSM_RELEASE_PACKAGE_NAME }}" }'

  release-to-github:
    runs-on: ubuntu-latest
    needs: [ ssm-release, release-to-s3, release-version-image, release-adot-operator]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.sha }}

      - name: Generate release-note
        run: sh tools/release/generate-release-note.sh

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ needs.release-checking.outputs.version }}
          commitish: ${{ github.event.inputs.sha }}
          release_name: ${{ needs.release-checking.outputs.version }}
          body_path: release-note
          draft: true
          prerelease: true
